# Generated by Django 5.0.6 on 2024-08-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0020_alter_sub_admindt_subadmin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(default='156f3b59', max_length=8, unique=True),
        ),
    ]
