# Generated by Django 5.0.6 on 2024-08-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0030_alter_sub_admindt_subadmin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(default='7ed8c2b5', max_length=8, unique=True),
        ),
    ]
