# Generated by Django 5.0.6 on 2024-08-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_order_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_clientdt',
            name='paid_paln',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='a79bc911', max_length=8, unique=True),
        ),
    ]
