# Generated by Django 5.0.6 on 2024-08-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_order_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='0f8733a4', max_length=8, unique=True),
        ),
    ]
