# Generated by Django 5.0.6 on 2024-08-12 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderangelone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='ec0e6a49', max_length=8, unique=True),
        ),
    ]
