# Generated by Django 5.0.6 on 2024-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_orderangelone_created_at_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50)),
                ('tradingsymbol', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('ordertype', models.CharField(max_length=50)),
                ('orderstatus', models.CharField(max_length=50)),
                ('averageprice', models.FloatField()),
                ('transactiontype', models.CharField(max_length=50)),
                ('updatetime', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='36261a69', max_length=8, unique=True),
        ),
    ]
