# Generated by Django 5.0.6 on 2024-08-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_order_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_clientdt',
            name='client_option',
            field=models.CharField(choices=[('Alpha Wave', 'Alpha Wave'), ('Gamma Gains', 'Gamma Gains'), ('Beta Balance', 'Beta Balance'), ('Demo', 'Demo')], default='Alpha Wave', max_length=20),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='ac2dfa38', max_length=8, unique=True),
        ),
    ]
