# Generated by Django 5.0.6 on 2024-08-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_trade_client_option_alter_ind_clientdt_client_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_clientdt',
            name='client_option',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='client_option',
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='553d1f57', max_length=8, unique=True),
        ),
    ]
