# Generated by Django 5.0.6 on 2024-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_trade_group_selection_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='31bf2bad', max_length=8, unique=True),
        ),
    ]
