# Generated by Django 5.0.6 on 2024-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_clientdt',
            name='group_selection',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='group_selection',
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='8632cda9', max_length=8, unique=True),
        ),
    ]
