# Generated by Django 5.0.6 on 2024-08-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_ind_clientdt_group_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='f5e4a27b', max_length=8, unique=True),
        ),
    ]
