# Generated by Django 5.0.6 on 2024-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_clientdt',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ind_clientdt',
            name='selected_option',
            field=models.CharField(choices=[('A', 'Alpha Wave'), ('B', 'Beta Balance'), ('C', 'Gamma Gains'), ('D', 'Demograph')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='ind_clientdt',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='4cf0b5e8', max_length=8, unique=True),
        ),
    ]
