# Generated by Django 5.0.6 on 2024-08-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_ind_clientdt_app_id_ind_clientdt_selected_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='41eb1d08', max_length=8, unique=True),
        ),
    ]
